version: 2 

sources:
  - name: raw
    schema: gz_raw_data
    description: original dataset in the raw format
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: table contains all sales information
        columns:
          - name: pdt_id
            description: id of the sales table should be unique and not - not_null
            tests:
              - not_null
      - name: product
        identifier: raw_gz_product
        description: table contains all product information
        columns:
          - name: products_id
            description: id of the sales table should be unique and not - not_null
            tests:
              - unique
              - not_null              
      - name: ship
        identifier: raw_gz_ship
        description: table contains all order information
        columns:
          - name: orders_id
            description: id of the sales table should be unique and not - not_null
            tests:
              - unique
              - not_null    

      - name: adwords
        identifier: raw_gz_adwords 
        description: table contains ad information
        columns:
          - name: date_date
            tests:
              - not_null 
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null                  
          - name: camPGN_name
            tests:
              - not_null    
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null 
          - name: click
            tests:
              - not_null
      - name: bing
        identifier: raw_gz_bing 
        description: table contains ad information
        columns:
          - name: date_date
            tests:
              - not_null 
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null                  
          - name: camPGN_name
            tests:
              - not_null    
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null 
          - name: click
            tests:
              - not_null

      - name: criteo
        identifier: raw_gz_criteo 
        description: table contains ad information
        columns:
          - name: date_date
            tests:
              - not_null 
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null                  
          - name: camPGN_name
            tests:
              - not_null    
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null 
          - name: click
            tests:
              - not_null
      - name: facebook
        identifier: raw_gz_facebook 
        description: table contains ad information
        columns:
          - name: date_date
            tests:
              - not_null 
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null                  
          - name: camPGN_name
            tests:
              - not_null    
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null 
          - name: click
            tests:
              - not_null

models:
      - name: int_campaign
        description: all finance data at day granulairty
        columns:
          - name: date_date
            tests:
              - not_null 
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null                  
          - name: camPGN_name
            tests:
              - not_null    
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null 
          - name: click
            tests:
              - not_null